### ISSUE TITLE
你好，有个问题想请教一下，关于作业三事件抽取的论文实现中。

### ISSUE THREAD

**Issue by Keeplingshi** [h12345jack/nlp_hw123#1]
你好，有个问题想请教一下。在作业三事件抽取的论文实现中，你在事件分类的方法上采用的是文本分类的方法。但是这样如果一个句子含有两个事件，如何得到每个触发词所对应的事件？
我原本的理解是，事件分类应该事件识别过程中0,1标签中的1变成34类（事件的种类数）。但你这里好像只考虑了句子级别的事件类别所属，并不是触发词的。我的理解有错误吗？

**Comment by h12345jack** [comment]
你好，事实上，在文本分类的问题上，只是分类，没有触发词识别，我当时把作业分成两个任务分别写的。是3天的产物...

在这个作业上，有其他的同学有更好的方法，把问题当做一个问题实现的。

关于多分类，一个句子会对应多类。例如![](http://ww1.sinaimg.cn/large/8785ef6ejw1f5pcqsiu3xj210m07otdc.jpg)
